# Generated by Django 4.0.6 on 2022-09-07 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_sending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Message text')),
                ('subject', models.TextField(blank=True, help_text='Message text')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
                ('receiver', models.TextField(blank=True, help_text='Phone numbers', null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'creation_time'], name='messages_se_receive_63f455_idx'),
        ),
    ]
